HTTP/1.1 200 - OK
x-powered-by: Express
content-type: application/json; charset=utf-8
content-length: 30
etag: W/"1e-GnkxrUdeXNJvnHv7ScztiHnOhFg"
date: Tue, 09 May 2023 16:56:14 GMT
connection: close

{
  "accessToken": "random-token"
}